### ISSUE TITLE
the documentation is wrong on your python index page.

### ISSUE THREAD

**Issue by lpbrown999** [fingul/myyoutube#1]
The version you forked uses kwargs instead of positional arguments. The documentation you provide implies that the user should use positional arguments.

**Comment by fingul** [comment]
No. it don`t imply positional argument. It just keyword argument.

> This function is of the form uploader.upload(file,**kwargs).
> 
> Only the file parameter is required for the upload to occur, as all other parameters have defaults which will be used should the argument not be passed, however it is recommended to pass the arguments in order to upload an attractive youtube video.
